import type { Metadata } from "next";
import NavBar from "@/components/Navbar";
import "./globals.css";
import Header from "@/components/Header";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="cmyk">
      <body> 
      <Header/>
      <NavBar>
        {children}
        </NavBar>
      </body>
    </html>
  );
}
